### ISSUE TITLE
MAINT: rename s3_path to s3_key

### ISSUE THREAD

**Issue by bsipocz** [fornax-navo/fornax-cloud-access-API#11]
I would think calling the bucket and key are more consistent, but it's not a strong preference.

**Comment by bsipocz** [comment]
So, apparenetly to be more consistent, we may also want to rename all `bucket` naming to `bucket_name`. 

How would you @zoghbi-a feel about this? This would mean to call the relevant fields in the json `bucket_name` and `key` instead of `bucket` and `path`, and everywhere inside the code (and then in the info properties, too).

**Comment by bsipocz** [comment]
(I have already made most of the changes, but then became uncertain whether this is something you would want to go ahead with).

**Comment by zoghbi-a** [comment]
I don't have a strong preference here. `key` seems to be the one used in aws. So please go ahead.
